name: Disable Workflow

on:
  push:
    branches:  [ main ]


jobs:
  disables:
    runs-on: ubuntu-latest

    steps:
      - name: mahim
        run: echo "Workflow Disable Done"



        
      
 
